plugins {
    id 'java'
    id 'maven-publish'
}

group = 'yorickbm.skyblockaddon.core'
version = '10.0.0'
base {
    archivesName = 'SkyBlockAddon-Core'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    // Gson dependency
    implementation 'com.google.code.gson:gson:2.10.1' // latest stable version

    //Google cache dependency
    implementation 'com.google.guava:guava:32.1.2-jre' // latest stable version

    // Log4j API only — implementation provided by Forge at runtime
    compileOnly 'org.apache.logging.log4j:log4j-api:2.15.0'

    // JUnit for testing
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly 'org.apache.logging.log4j:log4j-api:2.15.0'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
    options.compilerArgs.add('-Xlint:unchecked')
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = project.base.archivesName.get()
            version = project.version
        }
    }
}
